# generated by cabal-rpm-2.0.10
# https://docs.fedoraproject.org/en-US/packaging-guidelines/Haskell/

%global debug_package %{nil}

%bcond_with tests

Name:           koji-install
Version:        0.3
Release:        0.1%{?dist}
Summary:        CLI tool for installing rpms directly from Fedora Koji

License:        BSD
Url:            https://hackage.haskell.org/package/%{name}
# Begin cabal-rpm sources:
Source0:        https://hackage.haskell.org/package/%{name}-%{version}/%{name}-%{version}.tar.gz
# End cabal-rpm sources

# Begin cabal-rpm deps:
BuildRequires:  ghc-Cabal-devel
BuildRequires:  ghc-rpm-macros
BuildRequires:  ghc-base-static
BuildRequires:  ghc-directory-static
%if 0%{?fedora}
BuildRequires:  ghc-extra-static
%endif
BuildRequires:  ghc-filepath-static
%if 0%{?fedora}
BuildRequires:  ghc-koji-static
BuildRequires:  ghc-rpm-nvr-static
BuildRequires:  ghc-simple-cmd-static
BuildRequires:  ghc-simple-cmd-args-static
BuildRequires:  ghc-xdg-userdirs-static
%endif
%if %{defined rhel}
BuildRequires:  ghc-devel
BuildRequires:  cabal-install > 1.18
BuildRequires:  openssl-devel
BuildRequires:  zlib-devel
%endif
# End cabal-rpm deps

%description
koji-install can install the latest koji build of a package locally.
By default it only downloads newer binaries of the subpackages
already installed, but there are options to override that.


%prep
# Begin cabal-rpm setup:
%setup -q
# End cabal-rpm setup


%build
# Begin cabal-rpm build:
%if %{defined fedora}
%ghc_bin_build
%else
cabal update
%if 0%{?rhel} && 0%{?rhel} < 9
cabal sandbox init
cabal install
%endif
%endif
# End cabal-rpm build


%install
# Begin cabal-rpm install
%if %{defined fedora}
%ghc_bin_install
%else
mkdir -p %{buildroot}%{_bindir}
%if 0%{?fedora} >= 33 || 0%{?rhel} > 8
cabal install --install-method=copy --installdir=%{buildroot}%{_bindir}
%else
for i in .cabal-sandbox/bin/*; do
strip -s -o %{buildroot}%{_bindir}/$(basename $i) $i
done
%endif
%endif
mkdir -p %{buildroot}%{_datadir}/bash-completion/completions/
%{buildroot}%{_bindir}/%{name} --bash-completion-script %{name} | sed s/filenames/default/ > %{buildroot}%{_datadir}/bash-completion/completions/%{name}
# End cabal-rpm install


%check
%if %{with tests}
%cabal_test
%endif


%files
# Begin cabal-rpm files:
%license LICENSE
%doc ChangeLog.md README.md
%{_bindir}/%{name}
%{_datadir}/bash-completion/completions/%{name}
# End cabal-rpm files


%changelog
* Fri Dec  3 2021 Jens Petersen <petersen@redhat.com> - 0.3-0.1
- add `--list` command to list recent builds
- fix bug in generating kojifiles url from short name
- workarounds for rpmfusion's older koji not supporting patterns
- check if %dist is defined

* Fri Dec  3 2021 Jens Petersen <petersen@redhat.com> - 0.2.0-0.1
- 0.2.0

* Thu Aug 12 2021 Jens Petersen <petersen@redhat.com> - 0.1.0-1
- spec file generated by cabal-rpm-2.0.10
